# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='checked',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='filePath',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='inProcess',
            field=models.TextField(blank=True, null=True),
        ),
    ]
