# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170415_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='lastName',
            new_name='address',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
