# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170423_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='legal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('privacy', models.TextField(blank=True, null=True)),
                ('term_use', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'legal',
            },
        ),
    ]
