# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_legal'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filepath', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
