# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
