# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_complaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
